### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by pjrola** [vojtasvoboda/oc-bugsnag-plugin#4]
Just installed the plugin for October CMS and I am having issues installing. Here is the error message.

> Class 'Bugsnag\Client' not found

> /Users/prola/Sites/october/plugins/vojtasvoboda/bugsnag/Plugin.php

 line 76

`$client = Client::make($api_key);`

I have a valid API key but it seems on save it creates an exception. Any thoughts?

Note you need to run a `composer install ` from the plugins directory. I would suggest updating the doc to reflect this. This is not an issue and can be closed.

**Comment by vojtasvoboda** [comment]
Thanks for reporting this issue. I've try it and it is true, vendor files were not installed. This is weird, because when you try my other plugin [Twig extensions](https://github.com/vojtasvoboda/oc-twigextensions-plugin) the vendors are automatically installed.

I send a question to OctoberCMS and I'll let you know.

**Comment by vojtasvoboda** [comment]
Hi @pjrola, I found the error (with October support).

At Bugsnag plugin I'm using [meadsteve/monosnag](https://github.com/meadsteve/MonoSnag) library which requires PHP 5.6 or better. But on OctoberCMS Market (where the plugin is built before deploy) there is PHP 5.5.9, which cause that vendor files are not included.

It works on your machine because you are apparently using PHP 5.6 or better.

I'll fix it, but I need some time to find previous library for 5.5.9.

**Comment by pjrola** [comment]
Ah, that's makes sense.Awesome job on the plugin btw!

**Comment by vojtasvoboda** [comment]
Hi Pjrola, I made a fix, could you please test it? Thanks a lot!

https://github.com/vojtasvoboda/oc-bugsnag-plugin/commit/7033aad3ea2a67f0859eb77099bc19de665da6ab

**Comment by vojtasvoboda** [comment]
I also made a pull request with tests: https://github.com/vojtasvoboda/oc-bugsnag-plugin/pull/5

**Comment by pjrola** [comment]
Looks good thank you!

**Comment by vojtasvoboda** [comment]
Hi, plugin update is ready in the market or in the backend of your web. Thanks again for reporting issue.
